# Generated by Django 3.2.9 on 2022-02-04 02:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0003_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 2, 13, 34, 221001, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
