# Generated by Django 3.2.9 on 2022-02-14 03:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0008_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 3, 45, 31, 569549, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
